create table if not exists game_team_stats (
	id serial primary key, 
	
	game_id integer references games(id),
	home_team_id integer references teams(id),
	away_team_id integer references teams(id),
	
	home_fg integer,
	home_fga integer,
	home_fg_pct float,
	home_fg3 integer,
	home_fg3a integer,
	home_fg3_pct float,
	home_ft integer,
	home_fta integer,
	home_ft_pct float,
	home_orb integer,
	home_drb integer,
	home_trb integer,
	home_ast integer,
	home_stl integer,
	home_blk integer,
	home_tov integer,
	home_pf integer,
	home_pts integer,
	
	away_fg integer,
	away_fga integer,
	away_fg_pct float,
	away_fg3 integer,
	away_fg3a integer,
	away_fg3_pct float,
	away_ft integer,
	away_fta integer,
	away_ft_pct float,
	away_orb integer,
	away_drb integer,
	away_trb integer,
	away_ast integer,
	away_stl integer,
	away_blk integer,
	away_tov integer,
	away_pf integer,
	away_pts integer,
	
	home_ts_pct float,
	home_efg_pct float,
	home_fg3a_per_fga_pct float,
	home_fta_per_fga_pct float,
	home_orb_pct float,
	home_drb_pct float,
	home_trb_pct float,
	home_ast_pct float,
	home_stl_pct float,
	home_blk_pct float,
	home_tov_pct float,
	home_off_rtg float,
	home_def_rtg float,
	
	away_ts_pct float,
	away_efg_pct float,
	away_fg3a_per_fga_pct float,
	away_fta_per_fga_pct float,
	away_orb_pct float,
	away_drb_pct float,
	away_trb_pct float,
	away_ast_pct float,
	away_stl_pct float,
	away_blk_pct float,
	away_tov_pct float,
	away_off_rtg float,
	away_def_rtg float
)