CREATE TABLE IF NOT EXISTS game
(
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "game_id" TEXT NOT NULL UNIQUE,
    "home_team" TEXT NOT NULL,
    "away_team" TEXT NOT NULL,
    "home_team_full_name" TEXT NOT NULL,
    "away_team_full_name" TEXT NOT NULL,
    "game_time" TIMESTAMP NOT NULL,
    "arena_name" TEXT,
    "attendance" INT,
    "game_url" TEXT,
    "home_fg" INT,
    "home_fga" INT,
    "home_fg_pct" FLOAT,
    "home_fg3" INT,
    "home_fg3a" INT,
    "home_fg3_pct" FLOAT,
    "home_ft" INT,
    "home_fta" INT,
    "home_ft_pct" FLOAT,
    "home_orb" INT,
    "home_drb" INT,
    "home_trb" INT,
    "home_ast" INT,
    "home_stl" INT,
    "home_blk" INT,
    "home_tov" INT,
    "home_pf" INT,
    "home_pts" INT,
    "away_fg" INT,
    "away_fga" INT,
    "away_fg_pct" FLOAT,
    "away_fg3" INT,
    "away_fg3a" INT,
    "away_fg3_pct" FLOAT,
    "away_ft" INT,
    "away_fta" INT,
    "away_ft_pct" FLOAT,
    "away_orb" INT,
    "away_drb" INT,
    "away_trb" INT,
    "away_ast" INT,
    "away_stl" INT,
    "away_blk" INT,
    "away_tov" INT,
    "away_pf" INT,
    "away_pts" INT,
    "home_ts_pct" FLOAT,
    "home_efg_pct" FLOAT,
    "home_fg3a_per_fga_pct" FLOAT,
    "home_fta_per_fga_pct" FLOAT,
    "home_orb_pct" FLOAT,
    "home_drb_pct" FLOAT,
    "home_trb_pct" FLOAT,
    "home_ast_pct" FLOAT,
    "home_stl_pct" FLOAT,
    "home_blk_pct" FLOAT,
    "home_tov_pct" FLOAT,
    "home_off_rtg" FLOAT,
    "home_def_rtg" FLOAT,
    "away_ts_pct" FLOAT,
    "away_efg_pct" FLOAT,
    "away_fg3a_per_fga_pct" FLOAT,
    "away_fta_per_fga_pct" FLOAT,
    "away_orb_pct" FLOAT,
    "away_drb_pct" FLOAT,
    "away_trb_pct" FLOAT,
    "away_ast_pct" FLOAT,
    "away_stl_pct" FLOAT,
    "away_blk_pct" FLOAT,
    "away_tov_pct" FLOAT,
    "away_off_rtg" FLOAT,
    "away_def_rtg" FLOAT,
    "season" INT NOT NULL,  -- which season
    "is_playoff" INT NOT NULL, -- is this a playoff game
    "result" INT NOT NULL
);