INSERT INTO game (
    "game_id", "home_team","away_team","home_team_full_name","away_team_full_name",
    "game_time","arena_name","attendance","game_url",
    "home_fg","home_fga","home_fg_pct","home_fg3","home_fg3a","home_fg3_pct",
    "home_ft","home_fta","home_ft_pct","home_orb","home_drb","home_trb",
    "home_ast","home_stl","home_blk","home_tov","home_pf","home_pts",
    "away_fg","away_fga","away_fg_pct","away_fg3","away_fg3a","away_fg3_pct",
    "away_ft","away_fta","away_ft_pct","away_orb","away_drb","away_trb",
    "away_ast","away_stl","away_blk","away_tov","away_pf","away_pts",
    "home_ts_pct","home_efg_pct","home_fg3a_per_fga_pct","home_fta_per_fga_pct",
    "home_orb_pct","home_drb_pct","home_trb_pct","home_ast_pct","home_stl_pct",
    "home_blk_pct","home_tov_pct","home_off_rtg","home_def_rtg",
    "away_ts_pct","away_efg_pct","away_fg3a_per_fga_pct","away_fta_per_fga_pct",
    "away_orb_pct","away_drb_pct","away_trb_pct","away_ast_pct","away_stl_pct",
    "away_blk_pct","away_tov_pct","away_off_rtg","away_def_rtg",
    "season","is_playoff","result"
    )
SELECT
    game_id,
    home_team,
    away_team,
    home_team_full_name,
    away_team_full_name,
    to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS') AS game_time,
    arena_name,
    NULLIF(attendance, '')::INT AS attendance,
    sg.game_url,
    home_fg::int,
    home_fga::int,
    home_fg_pct::float,
    home_fg3::int,
    home_fg3a::int,
    home_fg3_pct::float,
    home_ft::int,
    home_fta::int,
    home_ft_pct::float,
    home_orb::int,
    home_drb::int,
    home_trb::int,
    home_ast::int,
    home_stl::int,
    home_blk::int,
    home_tov::int,
    home_pf::int,
    home_pts::int,
    away_fg::int,
    away_fga::int,
    away_fg_pct::float,
    away_fg3::int,
    away_fg3a::int,
    away_fg3_pct::float,
    away_ft::int,
    away_fta::int,
    away_ft_pct::float,
    away_orb::int,
    away_drb::int,
    away_trb::int,
    away_ast::int,
    away_stl::int,
    away_blk::int,
    away_tov::int,
    away_pf::int,
    away_pts::int,
    home_ts_pct::float,
    home_efg_pct::float,
    home_fg3a_per_fga_pct::float,
    home_fta_per_fga_pct::float,
    home_orb_pct::float,
    home_drb_pct::float,
    home_trb_pct::float,
    home_ast_pct::float,
    home_stl_pct::float,
    home_blk_pct::float,
    home_tov_pct::float,
    home_off_rtg::float,
    home_def_rtg::float,
    away_ts_pct::float,
    away_efg_pct::float,
    away_fg3a_per_fga_pct::float,
    away_fta_per_fga_pct::float,
    away_orb_pct::float,
    away_drb_pct::float,
    away_trb_pct::float,
    away_ast_pct::float,
    away_stl_pct::float,
    away_blk_pct::float,
    away_tov_pct::float,
    away_off_rtg::float,
    away_def_rtg::FLOAT,
    CASE
		WHEN (
			(EXTRACT(MONTH FROM to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS')) > 9 AND
			EXTRACT(YEAR FROM to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS')) != 2020)
			OR
			(EXTRACT(MONTH FROM to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS')) >= 12 AND
			EXTRACT(YEAR FROM to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS')) = 2020)
			)
		THEN EXTRACT(YEAR FROM to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS')) + 1
		ELSE EXTRACT(YEAR FROM to_timestamp(game_time, 'YYYY-MM-DD HH24:MI:SS'))
		END AS season,
    CASE WHEN pu.game_url IS NULL THEN 0 ELSE 1 END AS is_playoff,
    CASE WHEN home_pts > away_pts THEN 1 ELSE 0 END AS result
FROM st_game sg
LEFT JOIN st_playoff_url pu ON sg.game_url = pu.game_url
ON CONFLICT (game_id) DO NOTHING;
