name: Deploy Lambdas to AWS

on:
  workflow_run:
    workflows: ["Linting"]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_lambdas:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy all lambdas
        run: |
          for lambda in $(find lambdas -mindepth 1 -maxdepth 1 -type d); do
            echo "Deploying $(basename $lambda)..."
            ./lambdas/deploy.sh $(basename $lambda)
          done
