name: Deploy Lambdas to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_lambdas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Find changed lambdas since last deployment
        id: changes
        run: |
          echo "Detecting changes in lambdas folder..."
          if git rev-parse last-deploy >/dev/null 2>&1; then
            base_ref=$(git rev-parse last-deploy)
          else
            base_ref=$(git rev-list --max-parents=0 HEAD)  # First commit if no tag found
          fi
          changed_lambdas=$(git diff --name-only $base_ref HEAD | grep '^lambdas/' | cut -d '/' -f 2 | sort -u)
          echo "Changed lambdas: $changed_lambdas"
          echo "changed_lambdas=$changed_lambdas" >> $GITHUB_ENV

      - name: Deploy changed lambdas
        if: env.changed_lambdas != ''
        run: |
          for lambda in $(echo ${{ env.changed_lambdas }}); do
            echo "Deploying $lambda..."
            ./lambdas/$lambda/deploy.sh
          done

      - name: Tag new deployment
        if: env.changed_lambdas != ''
        run: |
          git tag -f last-deploy
          git push --tags --force
