name: Sync DB to S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync_to_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync DB folder to S3
        run: aws s3 sync ./db s3://baskpipe/sqls/ --delete
